### ISSUE TITLE
Upstream to QMK

### ISSUE THREAD

**Issue by JohnAZoidberg** [FrameworkComputer/qmk_firmware#13]
- [ ] Check all items in PR checklist: [docs.qmk.fm/#/pr_checklist](https://docs.qmk.fm/#/pr_checklist)
- [x]  Reading key input via ADC
  - [x] Wait for upstream PRs to merge to master.
  - [x] https://github.com/ChibiOS/ChibiOS-Contrib/pull/355
  - [x] https://github.com/qmk/qmk_firmware/pull/19453
  - [x] Move to QMK API instead of ChibiOS API
- [ ] Get airplane button merged https://github.com/qmk/qmk_firmware/pull/19490
- [ ] Move defines in `keyboards/lotus/ansi/ansi.c` to elsewhere
- [ ] Create an abstraction for the serial number reading

**Comment by felurx** [comment]
Hey there!
First of all, I think it's amazing that you have this open-source and are developing out in the open!

Is it still the plan to upstream this? Having everything in the regular QMK firmware would be great, it'd make customization a lot easier.

It looks like this issue and a few others keep on getting closed as stale, maybe it'd make sense to configure an exemption or to add one of the labels that don't get auto-closed.
