### ISSUE TITLE
[Feature Request] Support Framework Laptop 13

### ISSUE THREAD

**Issue by ibotty** [FrameworkComputer/qmk_firmware#26]
### Feature Request Type

- [ ] Core functionality
- [ ] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [ ] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

### Description

It would be great to allow using qmk on the framework 13 as well.

**Comment by JohnAZoidberg** [comment]
Sorry, that's not possible.
The framework 13 does not have a dedicated keyboard controller chip that we could run QMK on.
It's controlled by the embedded controller. You can look at https://github.com/FrameworkComputer/EmbeddedController/ and build your own EC firmware with a customized keyboard layout. But it does not supported the advanced features of QMK.
