### ISSUE TITLE
keyboard.frame.work doesn't work?

### ISSUE THREAD

**Issue by iliabaranov** [FrameworkComputer/qmk_firmware#37]
### Describe the Bug

I can't get https://keyboard.frame.work/ to work well.

I flashed latest [0.2.9 release](https://github.com/FrameworkComputer/qmk_firmware/releases/tag/v0.2.9)

Keyboard itself works great. however the webpage above shows errors:

15:16:54.020
Error: Failed to open the device.
Device: Framework Laptop 16 Keyboard Module - ANSI
Vid: 0x32AC
Pid: 0x0012

15:16:54.041
Received invalid protocol version from device
Device: Framework Laptop 16 Keyboard Module - ANSI
Vid: 0x32AC
Pid: 0x0012

### Keyboard Used

The official Framework 16 RGB English Keyboard

### Operating System

Ubuntu 22.04

### Is AutoHotKey / Karabiner installed

- [ ] AutoHotKey (Windows)
- [ ] Karabiner (macOS)

**Comment by gjabell** [comment]
I just ran into this issue as well and the errors seem to be a red herring if the browser doesn't have access to the underlying device (you can check this via `chrome://device-log` in chromium-based browsers). In my case, adding the qmk udev rules as mentioned in https://github.com/FrameworkComputer/qmk_hid#running-on-linux fixed the issue and the website now loads correctly.

**Comment by iliabaranov** [comment]
That was totally it! It's so obvious now! Thanks! :D 
Closing
