### ISSUE TITLE
Measure and improve latency

### ISSUE THREAD

**Issue by JohnAZoidberg** [FrameworkComputer/qmk_firmware#8]
Using `#define DEBUG_MATRIX_SCAN_RATE` in `config.h` prints the matrix scans every second.
Currently we're at 107Hz. If `matrix_scan_custom` returns immediately it's about 45kHz.

Approaches:

- [ ] Don't scan temperature (at least not every ADC conversion)
- [ ] Reduce buffer depth
- [ ] Check how much we actually need to sleep after selecting a row with the mux

References:

- https://michael.stapelberg.ch/posts/2021-05-08-keyboard-input-latency-qmk-kinesis/

**Comment by sruggier** [comment]
> Also consider using the per key `asym_eager_defer_pk` de-bouncing algorithm instead of the default global de-bouncing implementation. https://docs.qmk.fm/#/feature_debounce_type?id=selecting-an-included-debouncing-method

I tried using `sym_eager_pk` on my FL16 keyboard this evening (while testing increased debounce time), and found that it resulted in spurious events getting emitted for other unrelated keys as I was typing, keys my fingers were nowhere near, and not necessarily in the same row. So the per-key debounce types would probably lead to extra problems for some keyboards (any that are as noisy as mine) if they were part of the default configuration.

If I understand correctly, it might be enough to use an algorithm that's both eager and global, but that doesn't exist as a predefined option, so I couldn't justify spending the extra time to test it, as of now.
